#!/bin/sh
exec qemu-system-x86_64 -enable-kvm \
       -cpu host \
       -smp 4 \
       -bios /usr/share/edk2-ovmf/OVMF_CODE.fd \
       -drive file=/home/keke/QEMU/IMG/guix.img,if=virtio \
       -netdev user,id=vmnic,hostname=guix,hostfwd=tcp:192.168.2.140:2222-:22 \
       -device virtio-net,netdev=vmnic \
       -m 8G \
       -vga qxl \
       -vnc :1,password=on \
       -name "guix" \
       "$@"
