#!/bin/sh
exec qemu-system-x86_64 -enable-kvm \
       -cpu host \
       -bios /usr/share/edk2-ovmf/OVMF_CODE.fd \
       -drive file=/usr/share/drivers/windows/virtio-win.iso,media=cdrom \
       -drive file=/home/keke/QEMU/IMG/windows10.img,if=virtio \
       -netdev user,id=vmnic,hostname=archvm,hostfwd=tcp:192.168.2.140:22222-:3389 \
       -device virtio-net,netdev=vmnic \
       -m 4G \
       -vnc :0 \
       -name "win" \
       "$@"
